### ISSUE TITLE
Unnecessary printing of ID value

### ISSUE THREAD

**Issue by mattxyzeth** [jkomyno/nanoid#1]
https://github.com/jkomyno/nanoid/blob/30c81465692ea2649a9c2c2b323402d5217285ba/nanoid.go#L96

Is there a reason this is being printed? I'm working on cleaning up my log output and would like to avoid these.

Let me know if you want a pull request.

**Comment by jkomyno** [comment]
Thank you for noticing! I haven't used this library in a while, but you're right, that printing was absolutely useless.

**Comment by mattxyzeth** [comment]
Thanks for your quick response. Just one problem. The import wasn't removed and now the module is breaking my build.
